name: unp_connect
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.4.0
  cached_network_image: ^3.4.1
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  intl: ^0.19.0
  toastification: ^3.0.3
  audioplayers: ^6.5.1
  rxdart: ^0.28.0
  image_picker: ^1.2.1
  http: ^1.6.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#4C84ED"
  image: "assets/images/launch_screen_icon.png"
  android_12:
    image: "assets/images/launch_screen_icon.png"
    color: "#4C84ED"
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_medium.ttf
        - asset: assets/fonts/poppins_semibold.ttf
        - asset: assets/fonts/poppins_bold.ttf
